apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: ecommerce
type: Opaque
data:
  MONGO_URI: bW9uZ29kYitzcnY6Ly9uZXd1c2Vybm9vYjM3Ok1HNVNIWHhuN3NSYXJMVHZAY2x1c3RlcjAuZHVrdGUwcC5tb25nb2RiLm5ldC9lY29tbWVyY2VfZGI/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAK
  UPSTASH_REDIS_URL: cmVkaXNzOi8vZGVmYXVsdDpnUUFBQUFBQUFkM0JBQUlnY0RJd01qbGlNemMzTVRZeFl6STBObUZqWVRVMk1UQXlOMk5sTVRJNU9EWm1ZZ0BtYXNzaXZlLXNwb25nZS0xMjIzMDUudXBzdGFzaC5pbzo2Mzc5Cg==
  ACCESS_TOKEN_SECRET: YWNjZXNzX3Rva2VuX3NlY3JldAo=
  REFRESH_TOKEN_SECRET: cmVmcmVzaF90b2tlbl9zZWNyZXQK
  CLOUDINARY_CLOUD_NAME: ZGl0OGp6NXF3Cg==
  CLOUDINARY_API_KEY: NDY1MjEzODY2NDY2MzQ4Cg==
  CLOUDINARY_API_SECRET: aldOTTFkemhPd1dkNDVDMTVQb1JKOG5GaXc4Cg==
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVJqSEtVQ2hqT2gxeWlPN2N5aWtJRGgzUEtyUXJjTHFvOUxscGJkb1JUV2VaY1ZDRlBsZlQ3WGlETWdqRUIyeWVPTEF5eGNVbXVLZVkzTmxjSkdyeHdJRDAwcDlpNDN1bzgK
